require 'spec_helper'
require 'secryst/byt5_onnx'

RSpec.describe Secryst::Byt5Onnx do
  it 'uses the ByT5 byte conventions' do
    expect(Secryst::IMF::PAD_ID).to eq(0)
    expect(Secryst::IMF::EOS_ID).to eq(1)
  end

  describe 'byte round-trip (as used for generated output)' do
    it 'packs generated bytes back into UTF-8 text' do
      text = 'ភាសាខ្មែរ'
      bytes = text.bytes
      expect(bytes.pack('C*').force_encoding(Encoding::UTF_8)).to eq(text)
    end
  end
end
